docker_image            = docker://gromacs/gromacs:2022.2

# Artefact
executable              = run.sh
arguments               = $(protein)
transfer_input_files    = gromacs_pipeline.sh,mdp.tar.gz, pelican://chtc.wisc.edu/researchdrive/dbhaskar3/CHTC/sheaf_protein_dynamics/md_data.tar.gz
transfer_output_files   = md_data.tar.gz
transfer_output_remaps  = "md_data.tar.gz = pelican://chtc.wisc.edu/researchdrive/dbhaskar3/CHTC/sheaf_protein_dynamics/md_data.tar.gz" 

output                  = condor_log/output.$(Cluster)-$(Process).txt
error                   = condor_log/error.$(Cluster)-$(Process).txt
log                     = condor_log/log.$(Cluster)-$(Process).txt

# Compute resources
request_cpus            = 8
request_memory          = 16GB
request_disk            = 50GB

# Extra GPU settings
request_gpus            = 1
Requirements            = (Target.CUDADriverVersion >= 12.0)

# for non-DAG use
queue protein from (
6vxx
)
# for DAG use
#queue 1 
