shell = ./train.sh

log = train_$(Cluster)_$(Process).log
error = train_$(Cluster)_$(Process).err
output = train_$(Cluster)_$(Process).out

should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
Requirements = (Target.HasCHTCStaging == true)

Requirements = (Machine == "gpu2001.chtc.wisc.edu") || (Machine == "gpu2000.chtc.wisc.edu")



transfer_input_files = train.sh, .tar.gz, pelican://chtc.wisc.edu/researchdrive/dbhaskar3/CHTC/sheaf_protein_dynamics/surffold_data.tar.gz, file:///staging/groups/bhaskar_group/sheaf_protein_dynamics/surffold_data.tar.gz, pelican://chtc.wisc.edu/researchdrive/dbhaskar3/CHTC/sheaf_protein_dynamics/cath.tar.gz

gpus_maximum_capability = 7.5
request_cpus = 1
request_memory = 64GB
request_disk = 258GB
request_gpus = 1
queue 1
