docker_image = cmikulski4/sheaf_training:v2.8
universe = docker


shell = ./train.sh 

log = train_$(Cluster)_$(Process).log
error = train_$(Cluster)_$(Process).err
output = train_$(Cluster)_$(Process).out

should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
Requirements = (Target.HasCHTCStaging == true)



transfer_input_files = train.sh, train.py, gvp-pytorch.tar.gz, file:///staging/groups/bhaskar_group/sheaf_protein_dynamics/surffold_data.tar.gz, ../../lib/stats_utils.py

request_cpus = 1
request_memory = 64GB
request_disk = 258GB
request_gpus = 1

queue 1
