docker_image = jenslundsgaard/sheaf_training:v3.2

universe = docker

shell = ./download_pdbs_atlas.sh

log = download_pdbs_atlas_$(Cluster)_$(Process).log
error = download_pdbs_atlas_$(Cluster)_$(Process).err
output = download_pdbs_atlas_$(Cluster)_$(Process).out
#should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
Requirements = (Target.HasCHTCStaging == true) && (Machine == "bhaskargpu4000.chtc.wisc.edu")

transfer_input_files = download_pdbs_atlas.sh, download_pdbs_atlas.py, ../lib/, load_dynamics.py, pelican://chtc.wisc.edu/researchdrive/dbhaskar3/CHTC/sheaf_protein_dynamics/atlas_cross_val_index.csv
transfer_output_files = atlas_pdbs.tar.gz
transfer_output_remaps = "atlas_pdbs.tar.gz = pelican://chtc.wisc.edu/researchdrive/dbhaskar3/CHTC/sheaf_protein_dynamics/atlas_pdbs.tar.gz"

request_cpus = 16
request_memory = 32GB
request_disk = 64GB

queue 1
