
docker_image = jenslundsgaard/sheaf_training:v3.0

universe = docker
shell = ./get_csv_from_hdf5.sh

#  queue number assigned to this set of jobs at the time of submission.
log = get_csv_from_hdf5_$(Cluster)_$(Process).log
error = get_csv_from_hdf5_$(Cluster)_$(Process).err
output = get_csv_from_hdf5_$(Cluster)_$(Process).out
#should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
Requirements = (Target.HasCHTCStaging == true)


transfer_input_files = get_csv_from_hdf5.sh, get_csv_from_hdf5.py, pelican://chtc.wisc.edu/researchdrive/dbhaskar3/CHTC/sheaf_protein_dynamics/atlas_data.h5
transfer_output_files = atlas_cross_val_index.csv
transfer_output_remaps = "atlas_cross_val_index.csv = pelican://chtc.wisc.edu/researchdrive/dbhaskar3/CHTC/sheaf_protein_dynamics/atlas_cross_val_index.csv"

request_cpus = 1
request_memory = 16GB
request_disk = 128GB


queue 1

