# load_dynamics.sub

docker_image = jenslundsgaard/sheaf_training:v3.1

universe = docker

shell = ./load_dynamics.sh 

log = load_dynamics_$(Cluster)_$(Process).log
error = load_dynamics_$(Cluster)_$(Process).err
output = load_dynamics_$(Cluster)_$(Process).out

when_to_transfer_output = ON_EXIT_OR_EVICT
Requirements = (Target.HasCHTCStaging == true)


transfer_input_files = load_dynamics.py, load_dynamics.sh, file:///staging/groups/bhaskar_group/sheaf_protein_dynamics/atlas.csv

transfer_output_files = atlas_data.h5
transfer_output_remaps = "atlas_data.h5 = pelican://chtc.wisc.edu/researchdrive/dbhaskar3/CHTC/sheaf_protein_dynamics/atlas_data.h5"

# pelican://chtc.wisc.edu/researchdrive/dbhaskar3/CHTC/sheaf_protein_dynamics/atlas.csv,, 
# #pelican://chtc.wisc.edu/researchdrive/dbhaskar3/CHTC/sheaf_protein_dynamics/md_data.tar.gz"

request_cpus = 16
request_memory = 128GB
request_disk = 256GB

queue 1
