# load_dynamics.sub

docker_image = python:3.10-slim

universe = docker

shell = ./load_dynamics.sh 

log = load_dynamics_$(Cluster)_$(Process).log
error = load_dynamics_$(Cluster)_$(Process).err
output = load_dynamics_$(Cluster)_$(Process).out

should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
Requirements = (Target.HasCHTCStaging == true)


transfer_input_files = load_dynamics.py, load_dynamics.sh, file:///staging/groups/bhaskar_group/sheaf_protein_dynamics/atlas.csv
transfer_output_files = md_data.tar.gz
transfer_output_remaps = "md_data.tar.gz = file:///staging/groups/bhaskar_group/sheaf_protein_dynamics/md_data.tar.gz"
#pelican://chtc.wisc.edu/researchdrive/dbhaskar3/CHTC/sheaf_protein_dynamics/md_data.tar.gz"

request_cpus = 16
request_memory = 128GB
request_disk = 256GB

queue 1
