#train_residue_classifier_mdcath.sub
temp = 379

universe = docker
docker_image = jenslundsgaard/sheaf_training:v3.2
executable = train_residue_classifier.sh
arguments  = $(ablation) --ds-name mdcath --temp $(temp)

log    = train_residue_classifier_mdcath_$(Cluster)_$(Process).log
output = train_residue_classifier_mdcath_$(Cluster)_$(Process).out
error  = train_residue_classifier_mdcath_$(Cluster)_$(Process).err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

ResearchDrive = pelican://chtc.wisc.edu/researchdrive/dbhaskar3/CHTC/sheaf_protein_dynamics
transfer_input_files = train_residue_classifier.py, load_dynamics.py, ../lib/, ../../api_keys.txt, $(ResearchDrive)/mdcath_$(temp)_0_topo_split.csv, $(ResearchDrive)/mdcath_spinet_$(temp)_0_v2.h5
transfer_output_files = mdcath_laplacians.h5
transfer_output_remaps = "mdcath_laplacians.h5 = pelican://chtc.wisc.edu/researchdrive/dbhaskar3/CHTC/sheaf_protein_dynamics/mdcath_laplacians.h5"

+wantGPULab = true
request_cpus = 16
request_memory = 128GB
request_disk = 128GB
request_gpus = 1

requirements = (Target.HasCHTCStaging == true) && (Machine == "bhaskargpu4000.chtc.wisc.edu")

# it is not possible to insert temp as a variable in the txt file you need to specify it here
queue ablation from mdcath_ablations.txt
