# train.sub

docker_image = jenslundsgaard/scfold:v1.4

universe = docker

h5 = atlas_data.h5
index = atlas_cross_val_index.csv

#temp=320
#index=mdcath_$(temp)_0_topology_split.csv
#h5=mdcath_spinet_$(temp)_0.h5

shell = ./train.sh --h5-name $(h5) --index-name $(index) --use-pdbs

#  queue number assigned to this set of jobs at the time of submission.
log = train_$(Cluster)_$(Process).log
error = train_$(Cluster)_$(Process).err
output = train_$(Cluster)_$(Process).out

when_to_transfer_output = ON_EXIT_OR_EVICT
Requirements = (Target.HasCHTCStaging == true)
#  && (Machine == "bhaskargpu4000.chtc.wisc.edu")

transfer_input_files = train.sh, ScFold.tar.gz, pelican://chtc.wisc.edu/researchdrive/dbhaskar3/CHTC/sheaf_protein_dynamics/$(index), ../../../api_keys.txt
#pelican://chtc.wisc.edu/researchdrive/dbhaskar3/CHTC/sheaf_protein_dynamics/$(h5), 


request_cpus = 16
request_memory = 128GB
request_disk = 128GB
request_gpus = 1

queue 1
