# train.sub

docker_image = jenslundsgaard/scfold:v1.3

universe = docker
# Specify your executable (single binary or a script that runs several
#  commands) and arguments to be passed to jobs.
#  $(Process) will be a integer number for each job, starting with "0"
#  and increasing for the relevant number of jobs.
shell = ./train.sh

#  queue number assigned to this set of jobs at the time of submission.
log = train_$(Cluster)_$(Process).log
error = train_$(Cluster)_$(Process).err
output = train_$(Cluster)_$(Process).out

when_to_transfer_output = ON_EXIT_OR_EVICT
Requirements = (Target.HasCHTCStaging == true)
#  && (Machine == "bhaskargpu4000.chtc.wisc.edu")


transfer_input_files = train.sh, ScFold.tar.gz, pelican://chtc.wisc.edu/researchdrive/dbhaskar3/CHTC/sheaf_protein_dynamics/atlas_data.h5, pelican://chtc.wisc.edu/researchdrive/dbhaskar3/CHTC/sheaf_protein_dynamics/atlas_cross_val_index.csv
transfer_output_files = plots.tar.gz

request_cpus = 16
request_memory = 128GB
request_disk = 128GB
request_gpus = 1

queue 1
